---
title: "Preprocess and prepare data for simulation"
output: html_document
---

**Last updated:** `r Sys.Date()`

```{r, echo = FALSE}
knitr::read_chunk("chunks.R")
```

```{r knitr-opts-chunk, include=FALSE}
```


---

## Background and objectives

Preprocess data for simulation

1. Remove spike-in control genes.  
2. Remove genes and samples with zero count.  
3. Remove mitochrodrial genes.

---

## UMI protcols

### MouseZeiselBrain

```{r, eval = FALSE}
library(singleCellRNASeqMouseZeiselBrain)
eset <- get(data(MouseZeiselBrain))
ngenes <- nrow(eset)
nsamples <- ncol(eset)

# remove genes/samples with zero count
ii_genes_allzero <- rowSums(exprs(eset) == 0) == ngenes
ii_samples_allzero <- colSums(exprs(eset) == 0) == nsamples
table(ii_genes_allzero)
table(ii_samples_allzero)

# remove spike-in control genes
which_genes_control <- grep("ERCC", rownames(exprs(eset)))

# remove mitochrondrial genes
mito <- readRDS("../data/mitogenes.mouse.rds")
which_notmito <- which(!(rownames(exprs(eset)) %in% as.character(mito$Symbol)))

# make filtered dataset
eset_filtered <- eset[which_notmito, ]

# save to rds
saveRDS(exprs(eset_filtered), 
        file = "../data/mousezeiselbrain.rds")
```

### MouseKleinESC

```{r, eval = FALSE}
library(singleCellRNASeqMouseKleinESC)
eset <- get(data(MouseKleinESC))
ngenes <- nrow(eset)
nsamples <- ncol(eset)

# take samples from day 0 and day 7 of differentiation
daysToKeep <- which(pData(eset)$day == 0 |  pData(eset)$day == 7)
eset_tmp <- eset[,daysToKeep]

# remove genes/samples with zero count
ii_genes_allzero <- rowSums(exprs(eset_tmp) == 0) == ngenes
ii_samples_allzero <- colSums(exprs(eset_tmp) == 0) == nrow(eset_tmp)
table(ii_genes_allzero)
table(ii_samples_allzero)

# remove spike-in control genes
which_genes_control <- grep("ERCC", rownames(exprs(eset_tmp)))

# remove mitochrondrial genes
mito <- readRDS("../data/mitogenes.mouse.rds")
which_notmito <- which(!(rownames(exprs(eset_tmp)) %in% as.character(mito$Symbol)))

# make filtered dataset
eset_filtered <- eset_tmp[which_notmito, ]

# save to rds
saveRDS(exprs(eset_filtered), 
        file = "../data/mousekleinesc.rds")
```


### HumanTungiPSC

```{r, eval = FALSE}
library(singleCellRNASeqHumanTungiPSC)
eset <- get(data(HumanTungiPSC))
ngenes <- nrow(eset)
nsamples <- ncol(eset)

# remove genes/samples with zero count
ii_genes_allzero <- rowSums(exprs(eset) == 0) == ngenes
ii_samples_allzero <- colSums(exprs(eset) == 0) == nsamples
table(ii_genes_allzero)
table(ii_samples_allzero)

# remove spike-in control genes
which_genes_notcontrol <- grep("ERCC", rownames(exprs(eset)), invert = TRUE)

# remove mitochrondrial genes
mito <- readRDS("../data/mitogenes.human.rds")
which_notmito <- which(!(rownames(exprs(eset)) %in% as.character(mito$Symbol)))

# make filtered dataset
eset_filtered <- eset[unique(which_genes_notcontrol, which_notmito), ]

# save to rds
saveRDS(exprs(eset_filtered), 
        file = "../data/humantungipsc.rds")
```

---

## Full-length protocols

### Mouse Engel T cell

Take NKT0 and NKT17 cells.

```{r, eval = FALSE}
library(singleCellRNASeqMouseEngelTcell)
eset <- conquer_eset
ngenes <- nrow(eset)
nsamples <- ncol(eset)

# take NKT0 and NKT17
celltypesToKeep <- (pData(eset)$cell_type == "NKT0") | (pData(eset)$cell_type == "NKT17")
eset_tmp <- eset[,celltypesToKeep]

# check and remove genes/samples with zero count
# no genes with all zeros or samples with all zeros
ii_genes_allzero <- rowSums(exprs(eset_tmp) == 0) == ngenes
ii_samples_allzero <- colSums(exprs(eset_tmp) == 0) == nsamples
table(ii_genes_allzero)
table(ii_samples_allzero)

# remove spike-in control genes
which_genes_notcontrol <- grep("ERCC", rownames(exprs(eset_tmp)), invert = TRUE)

# remove mitochrondrial genes
mito <- readRDS("../data/mitogenes.mouse.rds")
which_notmito <- which(!(rownames(exprs(eset_tmp)) %in% as.character(mito$Symbol)))

# make filtered dataset
eset_filtered <- eset_tmp[unique(which_genes_notcontrol, which_notmito), ]

# round up the estimated counts
exprs(eset_filtered) <- round(exprs(eset_filtered))
# save to rds
saveRDS(exprs(eset_filtered), 
        file = "../data/mouseengeltcell.rds")
```



### Shalek Mouse 

TBD

```{r, eval = FALSE}
library(singleCellRNASeqMouseEngelTcell)
eset <- conquer_eset
ngenes <- nrow(eset)
nsamples <- ncol(eset)

# take NKT0 and NKT17
celltypesToKeep <- (pData(eset)$cell_type == "NKT0") | (pData(eset)$cell_type == "NKT17")
eset_tmp <- eset[,celltypesToKeep]

# check and remove genes/samples with zero count
# no genes with all zeros or samples with all zeros
ii_genes_allzero <- rowSums(exprs(eset_tmp) == 0) == ngenes
ii_samples_allzero <- colSums(exprs(eset_tmp) == 0) == nsamples
table(ii_genes_allzero)
table(ii_samples_allzero)

# remove spike-in control genes
which_genes_notcontrol <- grep("ERCC", rownames(exprs(eset_tmp)), invert = TRUE)

# remove mitochrondrial genes
mito <- readRDS("../data/mitogenes.mouse.rds")
which_notmito <- which(!(rownames(exprs(eset_tmp)) %in% as.character(mito$Symbol)))

# make filtered dataset
eset_filtered <- eset_tmp[unique(which_genes_notcontrol, which_notmito), ]

# save to rds
saveRDS(exprs(eset_filtered), 
        file = "../data/mouseengeltcell.rds")
```

---

## Session information

```{r, echo = FALSE}
sessionInfo()
```


